version: "3.7"

volumes:
  database:
    driver: local
networks:
  proxy:
    external: true
services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
    - 5430:5432
    volumes:
    - database:/var/lib/postgresql/data
  library:
    image: library:work
    build:
      context: ./Library.Web
      args:
        Environment: Work
    restart: always
    depends_on:
    - database
    networks:
    - proxy
    - default
    deploy:
      labels:
      - "com.docker.stack.image=library:work"
      - "com.docker.stack.namespace=library"
    ports:
    - 5000:80
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: tugolukov40@yandex.ru
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
    - pgadmin:/root/.pgadmin
    ports:
    - 4000:80
    networks:
    - proxy
    - default
    restart: unless-stopped