version: "3"
volumes:
  database:
    driver: local
networks:
  proxy:
    external: true
services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
    - 5430:5432
    volumes:
    - database:/var/lib/postgresql/data
  library:
    image: 130.193.35.45/library:work
    build:
      context: ./Library.Web
      args:
        Environment: Work
    restart: always
    depends_on:
    - database
    networks:
    - proxy
    - default
    deploy:
      labels:
      - "com.docker.stack.image=130.193.35.45/library:work"
      - "com.docker.stack.namespace=library"
    ports:
    - 4400:80